{{- if .Values.platformApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-app{{- if .Values.developmentApps.enabled }}-dev{{- end }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Seom1177/argocd-gitops-homelab.git
    targetRevision: {{ if .Values.developmentApps.enabled }}dev{{ else }}main{{ end }}
    path: platform/vault
    helm:
      valueFiles:
        - values.yaml
        {{- if .Values.developmentApps.enabled }}
        - values-dev.yaml
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Retry=true
{{- end }}
