apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-external-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: vault-eso
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: vault
