apiVersion: batch/v1
kind: Job
metadata:
  name: vault-setup
  namespace: vault
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: vault-setup-sa
      containers:
        - name: setup
          image: alpine/k8s:1.31.0
          env:
            - name: VAULT_ADDR
              value: "https://vault-app.vault.svc:8200"
            - name: VAULT_CACERT
              value: "/vault/userconfig/vault-tls/ca.crt"
            - name: TLS_SERVER_NAME
              value: "vault"
          command: ["/bin/sh", "/scripts/setup-vault.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: vault-tls
              mountPath: /vault/userconfig/vault-tls
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: vault-setup-script
            defaultMode: 0755
        - name: vault-tls
          secret:
            secretName: vault-tls
      restartPolicy: OnFailure
